apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - namespace.yaml
  - helm-chart.yaml

patches:
# Change restartPolicy for gitea-test-connection to OnFailure
  - patch: |-
        apiVersion: v1
        kind: Pod
        metadata:
          name: "gitea-test-connection"
        spec:
          restartPolicy: OnFailure